### ISSUE TITLE
UnboundLocalError: local variable 'price_difference' referenced before assignment

### ISSUE THREAD

**Issue by figgew** [donewiththedollar/directional-scalper#12]
Just pulled the latest update and got this - guessing a small bug?

Traceback (most recent call last):
  File "/home/trader/ds/bot.py", line 1256, in <module>
    hedge_mode_func(args.symbol)
  File "/home/trader/ds/bot.py", line 1205, in hedge_mode_func
    trade_func(symbol)
  File "/home/trader/ds/bot.py", line 773, in trade_func
    long_profit_prices = calculate_long_profit_prices(long_pos_price, price_difference, price_scale)
UnboundLocalError: local variable 'price_difference' referenced before assignment

**Comment by donewiththedollar** [comment]
Possibly just fixed :)

**Comment by figgew** [comment]
Great, thanks!
